spring:
  datasource:
    username: root
    password: MxtNx1y3y
    url: jdbc:mysql://127.0.0.1:3306/job?useUnicode=true&allowMultiQueries=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 8089
